version: '3.8'

services:
  graphics-generator:
    build:
      context: "https://github.com/Hnuti-kruh/generator.git#main"
      dockerfile: Dockerfile
    container_name: graphics-generator-app
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: generator.hnutikruh.cz
      VIRTUAL_PORT: 3000
      VIRTUAL_PROTO: http
      LETSENCRYPT_HOST: generator.hnutikruh.cz
      LETSENCRYPT_EMAIL: mtk@hnutikruh.cz
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal
      - nginx-proxy #aaaaa

networks:
  internal:
  nginx-proxy:
    external: true
    name: nginx-proxy
