version: '3.8'

services:
  graphics-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphics-generator-app
    restart: unless-stopped
    expose:
      - "3000"  # Exponujeme port 3000 pro nginx-proxy (serve default port)
    environment:
      - NODE_ENV=production
      # --- proxy nastavení ---
      - VIRTUAL_HOST=generator.hnutikruh.cz
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=http
      # Pokud používáte letsencrypt companion:
      - LETSENCRYPT_HOST=generator.hnutikruh.cz
      - LETSENCRYPT_EMAIL=mtk@hnutikruh.cz
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal
      - nginx-proxy

networks:
  internal:
  nginx-proxy:
    name: nginx-proxy
    external: true
